previewsEnabled: true
services:
  - type: web
    plan: standard
    name: app
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: my_env
        value: 27bed0121b936f977122d02fa7a45c7d